# Source

From video: www.youtube.com/watch?v=x9JiIFvlUwk&t<br>
Complete Pytorch Tensor Tutorial (Initializing Tensors, Math, Indexing, Reshaping)<br>
by Aladdin Persson

In [98]:
import torch
import numpy as np

# Device

In [2]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpuy'

In [3]:
print(DEVICE)

cuda


# Initialization 

### on GPU

In [321]:
# set directly to gpu
my_tensor = torch.tensor([ [1,2,3],[4,5,6] ],
                         device='cuda')
print(my_tensor)
print(my_tensor.shape) # method added to match numpy operation
print(my_tensor.size()) # same as shape
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.requires_grad)

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
torch.Size([2, 3])
torch.Size([2, 3])
torch.int64
cuda:0
False


### requires_grad

In [10]:
# note this fails as dtype is int64, must be float
my_tensor = torch.tensor([ [1,2,3],[4,5,6] ],
                         requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [11]:
# note works as typecasting to float
my_tensor = torch.tensor([ [1,2,3],[4,5,6] ],
                         requires_grad=True,
                        dtype=torch.float)
print(my_tensor)
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
torch.float32
cpu
True


### dtypes

_dtypes_ _available_ use as _torch_._DTYPE_<br>

float32 (default if using torch.float)<br>
float64<br>
float16<>br
int64 (default)<br>
int32<br>
int16<br>
bool (for boolean, only 0 maps to False)<br>

In [12]:
# default uses int64 if all values are only simple integers
my_tensor = torch.tensor([ [1,2,3],[4,5,6] ])
print(my_tensor.dtype)
print(my_tensor)
print(my_tensor.dtype)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [23]:
# defaults uses float32 if all values are treated as floats
# also if dtype specified as torch.float - see below
my_tensor = torch.tensor([ [1.,2,3],[4,5,6] ])
print(my_tensor)
print(my_tensor.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


In [24]:
# ints and floats

my_dtypes_list = [
    torch.int,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.float, # just float = float32
    torch.float16,
    torch.float32,
    torch.float64,
]

for dty in my_dtypes_list:
    my_tensor = torch.tensor([ [1,2,3],[4,5,6] ], dtype=dty)
    print(f"\n{dty}\t{my_tensor.dtype}")


torch.int32	torch.int32

torch.int16	torch.int16

torch.int32	torch.int32

torch.int64	torch.int64

torch.float32	torch.float32

torch.float16	torch.float16

torch.float32	torch.float32

torch.float64	torch.float64


### other common initialization methods

#### empty

In [54]:
# empty - will keep the ram position as they were
x = torch.empty(size = (3,3))
print(x)
print(x.dtype)

# empty like another tensor
x_existing = torch.tensor([ [1,2,3],[4,5,6] ])
print(x_existing)
print(x_existing.dtype)
x1 = torch.empty_like(x_existing)
print(x1)
print(x1.dtype)

tensor([[1.2466e-36, 0.0000e+00, 3.6568e+22],
        [4.5901e-41, 8.9683e-44, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 1.2467e-36]])
torch.float32
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
tensor([[         0,          0, 1629184272],
        [         0,          1,          6]])
torch.int64


#### zeros, ones, eye

In [35]:
# zeros
x = torch.zeros(size = (3,3))
print(x)

# ones
x = torch.ones(size = (3,3))
print(x)

# identity matrix
x = torch.eye(4,4) # note this can be a non-square matrix too
print(x)
x = torch.eye(3,5) # note this can be a non-square matrix too
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


#### full fill_

In [315]:
x = torch.empty(2,3)
print(x)
print()
# create tensor of certain size and fill all the values as specified
x = torch.full((2,3), 3.14)
print(x)
print()
x.fill_(1.5)
print(x)

tensor([[3.6569e+22, 4.5901e-41, 1.8177e+20],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])

tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]])


#### contiguous

Returns a contiguous in memory tensor containing the same data as self tensor. If self tensor is already in the specified memory format, this function returns the self tensor.

In [337]:
x = torch.rand(3,2).t()
print(x.shape)

y = x.contiguous()

torch.Size([2, 3])


#### arange, linspace

In [47]:
# arange - only end parameter is used
x = torch.arange(5)
print(x)

# arange - with explicit parameters
x = torch.arange(start=2, end=5, step=0.75)
print(x)

# linspace - create "step" number of elements. Note "end" value is inclusive
x = torch.linspace(start=0.1, end=0.85, steps=5)
print(x)
print(f"no. of elements = {x.numel()}")

tensor([0, 1, 2, 3, 4])
tensor([2.0000, 2.7500, 3.5000, 4.2500])
tensor([0.1000, 0.2875, 0.4750, 0.6625, 0.8500])
no. of elements = 5


#### simple rand vs random values from different distributions

In [70]:
# uniform - between 0 and 1 by default
x = torch.rand(3,3)
print(x)

# uniform - between specific values
x = torch.empty(size=(3, 3)).uniform_(-0.45, 0.15)
print(x)

# normal distribution
x = torch.empty(size=(2, 5)).normal_(mean=1.0, std=0.5)
print(x)

tensor([[0.2577, 0.1123, 0.6626],
        [0.4762, 0.7345, 0.4776],
        [0.7827, 0.3807, 0.4164]])
tensor([[-0.1437, -0.2924, -0.3005],
        [-0.1961,  0.1489,  0.0631],
        [-0.2029, -0.1476, -0.2286]])
tensor([[ 1.4178,  1.4186,  0.2833,  1.2737,  0.4618],
        [ 0.5030, -0.0412,  1.2009,  1.0893,  0.8408]])


In [58]:
# torch.normal

# Returns a tensor of random numbers drawn from separate normal
#   distributions whose mean and standard deviation are given.
# Note the mean and std parameters can be tensors themselves, then
#   elementwise matching of (mean, std) is done for each value.
#   Otherwise, give only one value to draw from same distribution.

In [59]:
# FAILS as at least one of them must be a tensor
x = torch.normal(mean=2.5, std=0.5)
print(x)

TypeError: normal() received an invalid combination of arguments - got (std=float, mean=float, ), but expected one of:
 * (Tensor mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, *, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [64]:
# one value only
x = torch.normal(mean=2.5, std=torch.tensor(0.5))
print(x)

# 4 values with same mean but different std
x = torch.normal(mean=2.5, std=torch.tensor([0.5, 2.0, 10.0, 100.0]))
print(x)

# 4 values with different means and different std
x = torch.normal(mean=torch.tensor([0.0, 2.5, 10.0, 20.0]), std=torch.tensor([0.5, 2.0, 10.0, 100.0]))
print(x)

tensor(2.8794)
tensor([  1.6075,   3.3080,  -5.1479, 230.1286])
tensor([  0.1937,   2.0393,   7.9612, -12.3243])


#### diagonal initialization

In [94]:
# If input is a vector (1-D tensor), then returns a 2-D tensor
#   with the elements of input as the diagonal.

diag_vals = torch.tensor([20,15,10])

# without specifying diagonal parameter,
#   uses diagnoal=0 by default and assigns values to main diagonal,
#   returns square matrix

x = torch.diag(diag_vals) 
print(x)

# to get non-square matrices, specify the diagonal parameter value
# diagonal > 0 , it is above main diagonal
x = torch.diag(diag_vals, diagonal=2)
print(x)
# diagonal > 0 , it is below main diagonal
x = torch.diag(diag_vals, diagonal=-1)
print(x)

# using like this equivalent to eye method
x = torch.diag(torch.ones(3))
print(x)


# If input is a matrix (2-D tensor), then returns a 1-D tensor with
#   the diagonal elements of input.
# Note: input need not be a square matrix only

x = torch.arange(start=15, end=30).reshape(3,5)
print(x)

# extract main diagonal
#   equivalent to diagnonal=0
print(x.diag())

# extract specified diagonal
print(x.diag(diagonal=-1))
print(x.diag(diagonal=4))

tensor([[20,  0,  0],
        [ 0, 15,  0],
        [ 0,  0, 10]])
tensor([[ 0,  0, 20,  0,  0],
        [ 0,  0,  0, 15,  0],
        [ 0,  0,  0,  0, 10],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]])
tensor([[ 0,  0,  0,  0],
        [20,  0,  0,  0],
        [ 0, 15,  0,  0],
        [ 0,  0, 10,  0]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])
tensor([15, 21, 27])
tensor([20, 26])
tensor([19])


#### initialize and convert to other types

In [97]:
t = torch.arange(4.) # float32 by default
print(t.dtype)

print(t.bool())

print(t.short()) # int16
print(t.long()) # int64
print(t.half()) # float16
print(t.float()) # float32
print(t.double()) # float64

torch.float32
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


#### Numpy to and fro Tensors

In [100]:
np_array = np.zeros((5,5))
t = torch.from_numpy(np_array)
print(t)
np_array_back = t.numpy()
print(type(np_array_back))
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
<class 'numpy.ndarray'>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Math and Compairson

In [101]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

## addition

In [111]:
z = x + y
print(z)

tensor([10, 10, 10])


In [109]:
z1 = torch.empty(3)
torch.add(x,y, out=z1)
print(z1)

tensor([10., 10., 10.])


In [110]:
z2 = torch.add(x, y)
print(z2)

tensor([10, 10, 10])


## subtraction

In [112]:
z = x - y
print(z)

tensor([-8, -6, -4])


## division

In [113]:
# element wise division if by equal shape
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [114]:
z = x / y
print(z)

tensor([0.1111, 0.2500, 0.4286])


## transpose

In [292]:
x = torch.arange(10).reshape(2,5)
print(x)
print()
print(x.t())

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])


## in-place operations

operation followed by _ means its an in-place operation

In [127]:
t = torch.zeros(3)
t.add_(x) # this is in-place
t

tensor([1., 2., 3.])

In [128]:
t += x # is in-place
t

tensor([2., 4., 6.])

In [129]:
t = t + x # NOT in-place
t

tensor([3., 6., 9.])

## exponentiation

In [146]:
print(x, y)

tensor([1, 2, 3]) tensor([9, 8, 7])


In [132]:
z = x ** 2 # value 2 is being broadcast here
print(z)

tensor([1, 4, 9])


In [134]:
# same as before by longer way
z = x.pow(2)
print(z)

tensor([1, 4, 9])


In [148]:
# element-wise exponentation
z = y ** x
print(z)

tensor([  9,  64, 343])


## simple comparison

In [135]:
z = x > 1
print(z)

tensor([False,  True,  True])


## multiplication

#### Matrix multiplication

In [160]:
x1 = torch.rand((2,5)) # 2x5
x2 = torch.rand((5,3)) # 5x3

x3 = torch.mm(x1, x2) # 2x3
print(x3)

x3 = x1.mm(x2) # same as before
print(x3)

tensor([[2.1266, 1.8037, 1.3765],
        [1.6554, 1.2083, 0.8900]])
tensor([[2.1266, 1.8037, 1.3765],
        [1.6554, 1.2083, 0.8900]])


#### Matrix exponentiation - multiple matrix by itself

In [137]:
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[1.2525, 1.9520, 1.8412, 1.1724, 1.8154],
        [0.2394, 0.3470, 0.3323, 0.2196, 0.3154],
        [3.5285, 5.0774, 4.8215, 3.2805, 4.8000],
        [1.5581, 2.3028, 2.1882, 1.4495, 2.1134],
        [2.5509, 3.7748, 3.5391, 2.3980, 3.5059]])


#### element wise multiplication

In [139]:
print(x , y)

tensor([1, 2, 3]) tensor([9, 8, 7])


In [140]:
z = x * y
print(z)

tensor([ 9, 16, 21])


In [141]:
#### dot product
z = torch.dot(x, y)
print(z)

tensor(46)


#### batch matrix multiplication

In [142]:
batch = 32
n, m, p = 10, 20, 30

In [143]:
t1 = torch.rand(batch, n, m) # 32x10x20
t2 = torch.rand(batch, m, p) # 32x20x30
t_bmm = torch.bmm(t1, t2) # 32x10x30
print(t_bmm.shape)

torch.Size([32, 10, 30])


## broadcasting

expands dimensions automatically as required to complete operation

In [144]:
x1 = torch.rand(5,5)
x2 = torch.rand(1,5)

z = x1 - x2 # works due to broadcasting

## other useful tensor operations

In [ ]:
#### get random permutation

In [170]:
torch.randperm(10)

tensor([9, 2, 3, 0, 8, 7, 1, 4, 5, 6])

#### sum across dimensions

In [177]:
a = torch.randperm(24).reshape(2,3,4)
a

tensor([[[11, 10,  3, 13],
         [19,  4, 14, 22],
         [ 1,  6, 21, 23]],

        [[ 0,  9,  7,  5],
         [17, 16, 20,  2],
         [18,  8, 15, 12]]])

In [178]:
sum_a = torch.sum(a) # ignore all dims and treat as flat vector
print(sum_a)

sum_a = torch.sum(a, dim=0) 
print(sum_a)
print(sum_a.shape)

sum_a = torch.sum(a, dim=1)
print(sum_a)
print(sum_a.shape)

sum_a = torch.sum(a, dim=2)
print(sum_a)
print(sum_a.shape)

tensor(276)
tensor([[11, 19, 10, 18],
        [36, 20, 34, 24],
        [19, 14, 36, 35]])
torch.Size([3, 4])
tensor([[31, 20, 38, 58],
        [35, 33, 42, 19]])
torch.Size([2, 4])
tensor([[37, 59, 51],
        [21, 55, 53]])
torch.Size([2, 3])


#### min and max - returns values and the indices

In [179]:
a = torch.randperm(6)
a

tensor([4, 1, 2, 3, 5, 0])

In [180]:
values, indices = torch.max(a, dim=0)
print(values)
print(indices)

tensor(5)
tensor(4)


In [185]:
a = torch.arange(24).reshape(2,3,4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [186]:
values, indices = torch.max(a, dim=0)
print(values)
print(indices)

print(f"\n")
values, indices = torch.max(a, dim=1)
print(values)
print(indices)

print(f"\n")
values, indices = torch.max(a, dim=2)
print(values)
print(indices)

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


tensor([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])


tensor([[ 3,  7, 11],
        [15, 19, 23]])
tensor([[3, 3, 3],
        [3, 3, 3]])


#### argmax argmix

In [189]:
a = torch.randperm(24).reshape(2,3,4)
a

tensor([[[11,  0, 22, 21],
         [10, 14, 18,  5],
         [13,  2,  6,  1]],

        [[15, 19,  9, 16],
         [23,  7, 17, 20],
         [12,  3,  4,  8]]])

In [190]:
indices = torch.argmax(a, dim=0)
print(indices)

print(f"\n")
indices = torch.argmax(a, dim=1)
print(indices)

print(f"\n")
print(f"\n")
indices = torch.argmax(a, dim=2)
print(indices)

tensor([[1, 1, 0, 0],
        [1, 0, 0, 1],
        [0, 1, 0, 1]])


tensor([[2, 1, 0, 0],
        [1, 0, 1, 1]])




tensor([[2, 2, 0],
        [1, 0, 0]])


In [191]:
indices = torch.argmin(a, dim=0)
print(indices)

print(f"\n")
indices = torch.argmin(a, dim=1)
print(indices)

print(f"\n")
print(f"\n")
indices = torch.argmin(a, dim=2)
print(indices)

tensor([[0, 0, 1, 1],
        [0, 1, 1, 0],
        [1, 0, 1, 0]])


tensor([[1, 0, 2, 2],
        [2, 2, 2, 2]])




tensor([[1, 3, 3],
        [2, 1, 1]])


 #### absolute value

In [183]:
a = torch.arange(-2, 3)
print(a)

abs_a = torch.abs(a)
print(abs_a)

tensor([-2, -1,  0,  1,  2])
tensor([2, 1, 0, 1, 2])


#### mean

Note: works only on floats

In [193]:
a = torch.arange(-2, 3)
print(a)

mean_a = torch.mean(a)
print(mean_a)

tensor([-2, -1,  0,  1,  2])


RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [197]:
a = torch.arange(-2, 3).float()
print(a)

mean_a = torch.mean(a, dim=0)
print(mean_a)

tensor([-2., -1.,  0.,  1.,  2.])
tensor(0.)


In [199]:
a = torch.arange(6).float().reshape(2,3)
print(a)

mean_a = torch.mean(a, dim=0)
print(mean_a)

mean_a = torch.mean(a, dim=1)
print(mean_a)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([1.5000, 2.5000, 3.5000])
tensor([1., 4.])


#### elementwise comparison

In [201]:
print(x, y)

z = torch.eq(x, y)
print(z)

tensor([1, 2, 3]) tensor([9, 8, 7])
tensor([False, False, False])


#### sorting

In [207]:
a = torch.randperm(8).reshape(2,4)
print(a)

sorted_a, indices = torch.sort(a, dim=0, descending=False)
print(sorted_a)
print(indices)

sorted_a, indices = torch.sort(a, dim=1, descending=True)
print(sorted_a)
print(indices)

tensor([[5, 1, 6, 7],
        [0, 3, 4, 2]])
tensor([[0, 1, 4, 2],
        [5, 3, 6, 7]])
tensor([[1, 0, 1, 1],
        [0, 1, 0, 0]])
tensor([[7, 6, 5, 1],
        [4, 3, 2, 0]])
tensor([[3, 2, 0, 1],
        [2, 1, 3, 0]])


#### clamp

In [208]:
a = torch.randperm(8).reshape(2,4)
print(a)

z = torch.clamp(a, min=1.5, max=6.5)
print(z)

tensor([[7, 2, 5, 3],
        [1, 0, 4, 6]])
tensor([[6, 2, 5, 3],
        [1, 1, 4, 6]])


In [ ]:
# torch.relu is special case of clamping equivalent
#  to torch.clamp(x, min=0)

#### any all

In [210]:
print(a)

z = torch.any(a) # any one value is truthy?
print(z)

z = torch.all(a) # all values truthy?
print(z)

tensor([[7, 2, 5, 3],
        [1, 0, 4, 6]])
tensor(True)
tensor(False)


# Indexing

In [234]:
batch_size = 3
features = 5

x = torch.arange(batch_size*features).reshape(batch_size, features)
print(x.shape)
print(x)

torch.Size([3, 5])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [272]:
# for all rows, take odd position elements
print(x[:, 0::2])

tensor([[ 0,  2,  4],
        [ 5,  7,  9],
        [10, 12, 14]])


In [231]:
# get all features of first batch
print(x[0]) # equivalent to x[0, :]

tensor([0, 1, 2, 3, 4])


In [232]:
# get only 2nd feature of all batchs
print(x[:, 1])

tensor([ 1,  6, 11])


In [243]:
# get certain features of certain batches
#   takes 2,1 and 1,4 positions returns 2 values
#   NOT the 2nd and 1st rows, columns positions 1 and
#      4 which would return 4 values
rows = torch.tensor([2, 1])
cols = torch.tensor([1, 4])
print(x[rows, cols])

tensor([11,  9])


#### extract based on conditions

In [271]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [266]:
print(x[ (x<3) | (x>10) ])

tensor([ 0,  1,  2, 11, 12, 13, 14])


In [267]:
print(x[ (3<x<10) ])

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [268]:
print(x[ (x>3) & (x<10) ])

tensor([4, 5, 6, 7, 8, 9])


In [270]:
# extract elements with remainder
print(x[ x.remainder(3) == 1 ])

tensor([ 1,  4,  7, 10, 13])


#### where

In [276]:
batch_size = 3
features = 5

x = torch.arange(batch_size*features).reshape(batch_size, features)
print(x)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [277]:
print(torch.where(x>7, x, x*2))

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14,  8,  9],
        [10, 11, 12, 13, 14]])


#### unique values

In [278]:
print(x.unique())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


#### dimensions shape numel

In [287]:
print(x.shape)
print()
print(x.ndimension())
print()
print(x.numel())
print(x.nelement())

torch.Size([3, 5])

2

15
15


# Reshaping

view - contiguous memory is used<br>
superior performance, but can fail if contiguous mem. not available

reshape - not contiguous<br>
slower, but always safer to use

In [293]:
x = torch.arange(9)

In [294]:
x_3x3 = x.view(3,3)
print(x_3x3.shape)

torch.Size([3, 3])


In [295]:
x_3x3 = x.reshape(3,3)
print(x_3x3.shape)

torch.Size([3, 3])


##### difference between view and reshape

https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch#:~:text=The%20semantics%20of%20reshape(),about%20the%20meaning%20of%20contiguous%20.

Reshape() can operate on both contiguous and non-contiguous tensor, while View() can ONLY operate on contiguous tensor.

torch.view will return a tensor with the new shape. The returned tensor will share the underling data with the original tensor.

torch.reshape MAY return a copy or a view of the original tensor.

To definitely COPY: use clone(), but to use the same storage use view().



In [334]:
# WORKS
x = torch.zeros(3,2)
print(x.shape)

y = x.t() # not a contiguous block
print(y.shape)

print(y.reshape(6))

torch.Size([3, 2])
torch.Size([2, 3])
tensor([0., 0., 0., 0., 0., 0.])


In [333]:
# FAILS
x = torch.zeros(3,2)
print(x.shape)

y = x.t() # not a contiguous block
print(y.shape)

print(y.view(6))

torch.Size([3, 2])
torch.Size([2, 3])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [335]:
# fix this using .contiguous

x = torch.zeros(3,2)
print(x.shape)

y = x.t() # not a contiguous block
print(y.shape)

print(y.contiguous().view(6)) # fixes as makes memory contiguous first

torch.Size([3, 2])
torch.Size([2, 3])
tensor([0., 0., 0., 0., 0., 0.])


## Concatenate

In [341]:
x1 = torch.rand(2,5)
x2 = torch.rand(2,5)
print(x1)
print(x2)
print()
x_cat_0 = torch.cat((x1,x2), dim=0)
print(x_cat_0)
print(x_cat_0.shape)
print()
x_cat_1 = torch.cat((x1,x2), dim=1)
print(x_cat_1)
print(x_cat_1.shape)

tensor([[0.4457, 0.2134, 0.1869, 0.0404, 0.9020],
        [0.9590, 0.7121, 0.6931, 0.9323, 0.7162]])
tensor([[0.7011, 0.1955, 0.2335, 0.8779, 0.2635],
        [0.1231, 0.1445, 0.3401, 0.1813, 0.2206]])

tensor([[0.4457, 0.2134, 0.1869, 0.0404, 0.9020],
        [0.9590, 0.7121, 0.6931, 0.9323, 0.7162],
        [0.7011, 0.1955, 0.2335, 0.8779, 0.2635],
        [0.1231, 0.1445, 0.3401, 0.1813, 0.2206]])
torch.Size([4, 5])

tensor([[0.4457, 0.2134, 0.1869, 0.0404, 0.9020, 0.7011, 0.1955, 0.2335, 0.8779,
         0.2635],
        [0.9590, 0.7121, 0.6931, 0.9323, 0.7162, 0.1231, 0.1445, 0.3401, 0.1813,
         0.2206]])
torch.Size([2, 10])


In [349]:
batch = 32
x1 = torch.rand(batch, 2, 5)
x2 = torch.rand(batch, 2, 5)
z = torch.cat((x1, x2), dim=0)
print(z.shape)

torch.Size([64, 2, 5])


## flatten or view

unroll into single vector<br>
can also use .view(-1)

In [347]:
batch = 32
x = torch.rand(batch, 2, 5)
print(x.shape)
print()
print(x.view(-1).shape)
print(x.shape)
print()
print(x.flatten().shape)
print()
batch = 32
x1 = torch.rand(batch, 2, 5)
z = x.view(batch, -1)
print(z.shape)

torch.Size([32, 2, 5])

torch.Size([320])
torch.Size([32, 2, 5])

torch.Size([320])

torch.Size([32, 10])


## permute

roll axis

In [350]:
batch = 32
x = torch.rand(batch, 2, 5)
z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([32, 5, 2])


## squeeze unsqueeze

add or remove dimensions

squeeze - returns tensor with all dimensions of size 1 removed

In [360]:
# unsqueeze
x = torch.arange(10).reshape(2,5)
print(x.shape)
print()
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
print()

# squeeze
x = torch.arange(10).unsqueeze(0).unsqueeze(0)
print(x.shape) # 1x1x10
print()
print(x.squeeze(0).shape)

torch.Size([2, 5])

torch.Size([1, 2, 5])
torch.Size([2, 1, 5])

torch.Size([1, 1, 10])

torch.Size([1, 10])


In [363]:
# squeeze
x = torch.arange(10).reshape(1,2,1,5)
print(x.shape)
print()
print(x.squeeze().shape) # works as looks at all positions with 1
print(x.squeeze(1).shape) # no effect as that position dim is not=1
print(x.squeeze(2).shape) # works as dim at that position is = 1
print()

torch.Size([1, 2, 1, 5])

torch.Size([2, 5])
torch.Size([1, 2, 1, 5])
torch.Size([1, 2, 5])

